version: '3'

services:

  app:
    build: 
      context: .
      network: host
    volumes:
      - .:/go/src
    networks:
      - app-network
      - rabbitmq-container_net_RMQ

  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - .pgdate:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=encoder
    ports:
      - "5432:5432"
    networks:
      - app-network

  # criado container do rabbitMq para ser compartilhado entre os MS´s
  # rabbit:
  #   image: "rabbitmq:3-management"
  #   environment:
  #     RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #     RABBITMQ_DEFAULT_USER: "rabbitmq"
  #     RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #     RABBITMQ_DEFAULT_VHOST: "/"
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"

networks:
  app-network:
    driver: bridge
  rabbitmq-container_net_RMQ:
    external: true